# -*- coding: utf-8 -*-
"""HOMR GUI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVyyf9HZ5UGWYGKBjO224ub13AwiloMZ
"""

import sys
import os
import warnings
import traceback

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

os.environ.setdefault("QT_LOGGING_RULES", "qt.qpa.fonts=false;qt.qpa.mime=false")
warnings.filterwarnings(
    "ignore",
    message=r"urllib3 .*doesn't match a supported version!",
    category=Warning,
    module=r"requests",
)

from homr.onnxruntime_utils import (
    configure_onnxruntime_logging,
    log_onnxruntime_status,
    preload_cuda_dlls,
)

preload_cuda_dlls()
configure_onnxruntime_logging(enable_debug=False)

from PyQt6.QtWidgets import (
    QApplication, QWidget, QPushButton, QVBoxLayout,
    QLabel, QGraphicsDropShadowEffect, QHBoxLayout
)
from PyQt6.QtCore import Qt, QMimeData, QUrl, QThread, pyqtSignal, QPoint, QTimer
from PyQt6.QtGui import (
    QDrag, QColor
)

# 【核心优化 1】把庞大的库和 AI 核心在软件启动时就加载进内存，一直待命！
from music21 import converter
from homr.main import process_image, ProcessingConfig
from homr.music_xml_generator import XmlGeneratorArguments

# ======================================================================
#  UI PARAMETERS (CFG) - Minimalist Swiss Dark Mode
# ======================================================================
CFG = {
    "WINDOW_SIZE": (230, 270),
    "MARGINS": (12, 24, 12, 7),        # 左右22, 上24, 下20 (Generous White Space)

    "RADIUS_WINDOW": 0,                 # 使用 Windows 原生窗口，无圆角
    "RADIUS_CARD": 24,                  # 内部卡片圆角

    "COLOR_BG": "#000000",              # 纯黑底色
    "COLOR_TEXT_TITLE": "#FFFFFF",
    "COLOR_TEXT_SUB": "#555555",
    "COLOR_TEXT_FOOTER": "#444444",

    "FONT_FAMILY": "'Helvetica Neue', 'Inter', 'Microsoft YaHei UI', sans-serif",
    "FONT_SIZE_TITLE": "26px",
    "FONT_SIZE_SUB": "10px",
    "FONT_SIZE_BTN_TITLE": "19px",      # 大字体引导
    "FONT_SIZE_BTN_SUB": "11px",
    "FONT_SIZE_FOOTER": "9px",

    # 4 种状态的色彩系统 (低饱和度粉彩色 + 高对比度黑色文字)
    "STATES": {
        "idle": {
            "title": "框选乐谱",
            "sub": "Win + Shift + S",
            "bg": "#8CA6BA",            # Muted Pastel Blue (莫兰迪蓝)
            "bg_hover": "#9EB5C7",
            "color": "#050505",         # 卡片上的极深色文字，凸显瑞士风
            "shadow_color": QColor(140, 166, 186, 0),    # 平常完全扁平化 (Alpha 0)
            "shadow_active": QColor(140, 166, 186, 140), # 按下时产生发光加深反馈
        },
        "processing": {
            "title": "解析中",
            "sub": "AI Engine Running",
            "bg": "#D9C88C",            # Muted Pastel Yellow (低饱和度芥末黄)
            "bg_hover": "#E6D6A1",
            "color": "#050505",
            "shadow_color": QColor(217, 200, 140, 0),
            "shadow_active": QColor(217, 200, 140, 140),
        },
        "success": {
            "title": "转换成功",
            "sub": "按住拖入 DAW",
            "bg": "#9AB593",            # Muted Pastel Green (柔和绿)
            "bg_hover": "#ADC9A6",
            "color": "#050505",
            "shadow_color": QColor(154, 181, 147, 0),
            "shadow_active": QColor(154, 181, 147, 140),
        },
        "error": {
            "title": "识别失败",
            "sub": "请重新截图",
            "bg": "#C78B8B",            # Muted Pastel Red (灰砖红)
            "bg_hover": "#D99C9C",
            "color": "#050505",
            "shadow_color": QColor(199, 139, 139, 0),
            "shadow_active": QColor(199, 139, 139, 140),
        }
    }
}
# ======================================================================

# ─────────────────────────────────────────────
#  重写后的核心逻辑：消除冷启动，速度起飞！
# ─────────────────────────────────────────────
class WorkerThread(QThread):
    finished = pyqtSignal(str)
    error = pyqtSignal(str)

    def __init__(self, img_path):
        super().__init__()
        self.img_path = img_path

    def run(self):
        try:
            # 1. 配置 HOMR 的运行参数 (直接在内存中对接你上传的 main.py 逻辑)
            use_gpu_inference = True
            log_onnxruntime_status(use_gpu_inference)
            config = ProcessingConfig(
                enable_debug=False,
                enable_cache=False,
                write_staff_positions=False,
                read_staff_positions=False,
                selected_staff=-1,
                use_gpu_inference=use_gpu_inference,
            )
            xml_args = XmlGeneratorArguments(False, None, None)

            # 2. 直接调用 AI 识别函数，不再启动黑框框新进程！
            process_image(self.img_path, config, xml_args)

            out_xml = os.path.splitext(self.img_path)[0] + ".musicxml"
            out_mid = os.path.splitext(self.img_path)[0] + ".mid"

            # 3. 将 MusicXML 转 MIDI
            # (此时 music21 已经在内存中，转换瞬间完成)
            if os.path.exists(out_xml):
                score = converter.parse(out_xml)
                score.write('midi', fp=out_mid)
                self.finished.emit(out_mid)
            else:
                self.error.emit("AI 识别完成，但未能生成 XML 文件")

        except Exception as e:
            # 捕获并输出详细错误，方便排查
            print(traceback.format_exc())
            self.error.emit(f"识别失败: {str(e)}")

# ─────────────────────────────────────────────
#  重构后的 GUI（纯粹的瑞士暗黑极简主义）
# ─────────────────────────────────────────────
class HomrGui(QWidget):
    _drag_pos = QPoint()

    def __init__(self):
        super().__init__()
        self.current_output = ""
        self.last_image_id = None
        self._clipboard_pending = False
        self.current_state_cfg = None
        self.initUI()
        QApplication.clipboard().dataChanged.connect(self.schedule_clipboard_check)

    # ── UI 初始化 ─────────────────────────────
    def initUI(self):
        self.setWindowTitle('HOMR · 乐谱转MIDI')
        self.setFixedSize(*CFG["WINDOW_SIZE"])
        self.setWindowFlags(
            Qt.WindowType.WindowStaysOnTopHint |
            Qt.WindowType.FramelessWindowHint
        )
        self.setStyleSheet("background-color: #000000;")

        # 最外层容器
        layout = QVBoxLayout(self)
        layout.setContentsMargins(*CFG["MARGINS"])
        layout.setSpacing(0)

        # ── 顶部 Header 区 (纯文本 Logo) ──
        header_layout = QHBoxLayout()
        header_layout.setAlignment(Qt.AlignmentFlag.AlignTop)

        title_layout = QVBoxLayout()
        title_layout.setSpacing(0)

        title_lbl = QLabel("HOMR.")
        title_lbl.setStyleSheet(f"""
            color: {CFG['COLOR_TEXT_TITLE']};
            font-family: {CFG['FONT_FAMILY']};
            font-size: {CFG['FONT_SIZE_TITLE']};
            font-weight: 900;
            letter-spacing: -1px;
            background-color: transparent;
        """)

        sub_lbl = QLabel("Score to MIDI")
        sub_lbl.setStyleSheet(f"""
            color: {CFG['COLOR_TEXT_SUB']};
            font-family: {CFG['FONT_FAMILY']};
            font-size: {CFG['FONT_SIZE_SUB']};
            font-weight: 700;
            letter-spacing: 0.5px;
            background-color: transparent;
        """)

        title_layout.addWidget(title_lbl)
        title_layout.addWidget(sub_lbl)

        header_layout.addLayout(title_layout)
        header_layout.addStretch()

        close_btn = QPushButton("×", self)
        close_btn.setFixedSize(24, 24)
        close_btn.setCursor(Qt.CursorShape.PointingHandCursor)
        close_btn.setStyleSheet(f"""
            QPushButton {{
                background: transparent;
                border: none;
                color: {CFG['COLOR_TEXT_SUB']};
                font-size: 22px;
                font-weight: 300;
                padding-bottom: 4px;
            }}
            QPushButton:hover {{ color: {CFG['COLOR_TEXT_TITLE']}; }}
        """)
        close_btn.clicked.connect(self.close)

        header_layout.addWidget(close_btn, alignment=Qt.AlignmentFlag.AlignTop)

        layout.addLayout(header_layout)
        layout.addSpacing(28) # Header 与大卡片的留白空间

        # ── 核心交互大卡片 (主按键) ──────────────
        self.btn = QPushButton(self)
        btn_w = self.width() - CFG["MARGINS"][0] - CFG["MARGINS"][2]
        self.btn.setFixedSize(btn_w, 120)
        self.btn.setCursor(Qt.CursorShape.PointingHandCursor)

        # 动态阴影组件 (默认状态为 Alpha 0，即 Flat UI)
        self.shadow = QGraphicsDropShadowEffect()
        self.shadow.setBlurRadius(0)
        self.shadow.setOffset(0, 8)
        self.btn.setGraphicsEffect(self.shadow)

        # 在 QPushButton 中嵌入排版布局，实现居中对齐文本
        self.btn_layout = QVBoxLayout(self.btn)
        self.btn_layout.setContentsMargins(20, 20, 20, 20)
        self.btn_layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_layout.setSpacing(1)

        self.btn_title = QLabel()
        self.btn_title.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents)
        self.btn_subtitle = QLabel()
        self.btn_subtitle.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents)

        self.btn_layout.addWidget(self.btn_title)
        self.btn_layout.addWidget(self.btn_subtitle)

        # 挂载交互事件
        self.btn.pressed.connect(self._on_btn_pressed)
        self.btn.released.connect(self._on_btn_released)
        self.btn.pressed.connect(self.start_drag)

        layout.addWidget(self.btn, alignment=Qt.AlignmentFlag.AlignCenter)
        layout.addSpacing(20)
        layout.addStretch()

        # ── 底部开发者/版权信息 (纯粹的非衬线小字排版) ──
        footer_layout = QVBoxLayout()
        footer_layout.setSpacing(2)

        dev = QLabel('GUI by <a href="https://b23.tv/oA1dZL5" style="color:#8CA6BA; text-decoration:none;">尤里uri</a>')
        dev.setOpenExternalLinks(True)
        dev.setStyleSheet(f"""
            color: {CFG['COLOR_TEXT_FOOTER']};
            font-family: {CFG['FONT_FAMILY']};
            font-size: {CFG['FONT_SIZE_FOOTER']};
            font-weight: 500;
            background-color: transparent;
        """)

        engine = QLabel("Powered by HOMR Engine")
        engine.setStyleSheet(f"""
            color: {CFG['COLOR_TEXT_FOOTER']};
            font-family: {CFG['FONT_FAMILY']};
            font-size: {CFG['FONT_SIZE_FOOTER']};
            font-weight: 600;
            background-color: transparent;
        """)

        footer_layout.addWidget(dev)
        footer_layout.addWidget(engine)

        layout.addLayout(footer_layout)

        # 载入初始态
        self._apply_state("idle")

    # ── 状态样式动态更新 ─────────────────────
    def _apply_state(self, state_name: str):
        c = CFG["STATES"].get(state_name, CFG["STATES"]["idle"])
        self.current_state_cfg = c

        # 1. 扁平化背景
        self.btn.setStyleSheet(f"""
            QPushButton {{
                background-color: {c['bg']};
                border-radius: {CFG['RADIUS_CARD']}px;
                border: none;
            }}
            QPushButton:hover {{
                background-color: {c['bg_hover']};
            }}
        """)

        # 2. 内部字体排版更新
        self.btn_title.setText(c['title'])
        self.btn_title.setStyleSheet(f"""
            color: {c['color']};
            font-family: {CFG['FONT_FAMILY']};
            font-size: {CFG['FONT_SIZE_BTN_TITLE']};
            font-weight: 800;
            letter-spacing: -0.5px;
            background-color: transparent;
        """)

        # 给副标题叠一点透明度，拉开层次
        sub_color = QColor(c['color'])
        sub_color.setAlpha(160)
        self.btn_subtitle.setText(c['sub'])
        self.btn_subtitle.setStyleSheet(f"""
            color: {sub_color.name(QColor.NameFormat.HexArgb)};
            font-family: {CFG['FONT_FAMILY']};
            font-size: {CFG['FONT_SIZE_BTN_SUB']};
            font-weight: 500;
            background-color: transparent;
        """)

        # 3. 恢复阴影重置态
        self.shadow.setColor(c['shadow_color'])

    # ── 点击交互特效：产生空间物理按压感 ────────
    def _on_btn_pressed(self):
        if self.current_state_cfg:
            # 点击时绽放厚重的光晕/阴影，保持对称 Padding，文字位置不偏移
            self.shadow.setColor(self.current_state_cfg['shadow_active'])
            self.shadow.setBlurRadius(32)
            self.shadow.setOffset(0, 12)

    def _on_btn_released(self):
        if self.current_state_cfg:
            # 释放时回归无阴影极简风
            self.shadow.setColor(self.current_state_cfg['shadow_color'])
            self.shadow.setBlurRadius(0)
            self.shadow.setOffset(0, 8)

    # ── 无边框窗口：鼠标拖动 ─────────────────
    def mousePressEvent(self, event):
        if event.button() == Qt.MouseButton.LeftButton:
            self._drag_pos = event.globalPosition().toPoint() - self.frameGeometry().topLeft()

    def mouseMoveEvent(self, event):
        if event.buttons() == Qt.MouseButton.LeftButton:
            self.move(event.globalPosition().toPoint() - self._drag_pos)

    # ─────────────────────────────────────────
    #  以下全部是原始核心逻辑，未动一行
    # ─────────────────────────────────────────
    def schedule_clipboard_check(self):
        if self._clipboard_pending:
            return
        self._clipboard_pending = True
        QTimer.singleShot(250, self.on_clipboard_change)

    def on_clipboard_change(self):
        self._clipboard_pending = False
        clipboard = QApplication.clipboard()
        mime_data = clipboard.mimeData()

        if mime_data.hasImage():
            img = clipboard.image()
            if img.isNull():
                return

            img_id = img.cacheKey()
            if img_id == self.last_image_id:
                return
            self.last_image_id = img_id

            self._apply_state("processing")

            img_path = os.path.abspath("temp_score.png")
            img.save(img_path)

            self.thread = WorkerThread(img_path)
            self.thread.finished.connect(self.on_process_success)
            self.thread.error.connect(self.on_process_error)
            self.thread.start()

    def on_process_success(self, out_file):
        if os.path.exists(out_file):
            self.current_output = out_file
            self._apply_state("success")
        else:
            self.on_process_error("找不到输出的 MIDI 文件")

    def on_process_error(self, err_msg):
        print("识别错误:", err_msg)
        self._apply_state("error")

    def start_drag(self):
        if not self.current_output or not os.path.exists(self.current_output):
            return

        drag = QDrag(self)
        mime_data = QMimeData()
        url = QUrl.fromLocalFile(self.current_output)
        mime_data.setUrls([url])
        drag.setMimeData(mime_data)

        drag.exec(Qt.DropAction.CopyAction)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = HomrGui()
    ex.show()
    sys.exit(app.exec())
